
version: "3.9"

services:
  ai-api:
    build:
      context: ./ai-api
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./ai-api:/app  # Mount the api folder into the container for live code updates.
    env_file:
      - .ai-api-env
  ai-ui:
    build:
      context: ./ai-ui
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./ai-ui:/app  # Mount the api folder into the container for live code updates.
    env_file:
      - .ai-ui-env
